name: DRep Voting Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fetch-drep-info:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run voting action script
      env:
        KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
      run: node voting-action.js